/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package misventanasenlazadas.vistas;

import java.awt.Color;
import java.awt.event.ActionListener;


/**
 *
 * @author Sergio Teacher
 */
public class MiVentanaConfig extends javax.swing.JDialog {


    /**
     * Creates new form MiVentanaConfig
     */
    public MiVentanaConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        System.out.println("lanzando dialogo personalizado ...");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelBotones = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanelCentral = new javax.swing.JPanel();
        jLabelTítulo = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        btnColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Config");

        jPanelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOk.setText("Ok");
        jPanelBotones.add(btnOk);

        btnCancel.setText("Cancel");
        jPanelBotones.add(btnCancel);

        getContentPane().add(jPanelBotones, java.awt.BorderLayout.PAGE_END);

        java.awt.GridBagLayout jPanelCentralLayout = new java.awt.GridBagLayout();
        jPanelCentralLayout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0};
        jPanelCentralLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanelCentral.setLayout(jPanelCentralLayout);

        jLabelTítulo.setText("Título:   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanelCentral.add(jLabelTítulo, gridBagConstraints);

        jLabelColor.setText("Color  -->");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanelCentral.add(jLabelColor, gridBagConstraints);

        jTextFieldTitulo.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanelCentral.add(jTextFieldTitulo, gridBagConstraints);

        btnColor.setBackground(new java.awt.Color(204, 204, 0));
        btnColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnColor.setText("Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanelCentral.add(btnColor, gridBagConstraints);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelTítulo;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables


    public String getTextoFieldTitulo() {
        return jTextFieldTitulo.getText();
    }

    public void ponColorjPanelCentral(Color c) {
        jPanelCentral.setBackground(c);
    }

    /**
    * Doy control selectivo, sólo a la capacidad de escuchar.
    */
    public void addActionListenerbtnColor(ActionListener l){
        btnColor.addActionListener(l);
    }
    /**
    * Doy control selectivo, sólo a la capacidad de escuchar.
    */
    public void addActionListenerbtnOk(ActionListener l){
        btnOk.addActionListener(l);
    }
    /**
    * Doy control selectivo, sólo a la capacidad de escuchar.
    */
    public void addActionListenerbtnCancel(ActionListener l){
        btnCancel.addActionListener(l);
    }

}

