/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misventanasenlazadas.vistas;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Sergio Teacher
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.setIconImage( new ImageIcon(getClass().getResource("/misventanasenlazadas/media/letter_j_PNG71.png")).getImage() );
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraHerramientas = new javax.swing.JToolBar();
        btnConf = new javax.swing.JButton();
        btnHija = new javax.swing.JButton();
        jPanelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana ...");

        BarraHerramientas.setBackground(new java.awt.Color(153, 204, 255));
        BarraHerramientas.setOrientation(javax.swing.SwingConstants.VERTICAL);
        BarraHerramientas.setRollover(true);

        btnConf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConf.setText("Conf");
        btnConf.setFocusable(false);
        btnConf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramientas.add(btnConf);

        btnHija.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHija.setText("Hija");
        btnHija.setFocusable(false);
        btnHija.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHija.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramientas.add(btnHija);

        getContentPane().add(BarraHerramientas, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JButton btnConf;
    private javax.swing.JButton btnHija;
    private javax.swing.JPanel jPanelCentral;
    // End of variables declaration//GEN-END:variables

    public void ponColorjPanelCentral(Color c) {
        jPanelCentral.setBackground(c);
    }

    /**
    * Doy control selectivo, sólo a la capacidad de escuchar.
    */
    public void addActionListenerbtnConf(ActionListener l){
        btnConf.addActionListener(l);
    }
    /**
    * Doy control selectivo, sólo a la capacidad de escuchar.
    */
    public void addActionListenerbtnHija(ActionListener l){
        btnHija.addActionListener(l);

    }

}

