/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misventanasenlazadas.vistas;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author Sergio Teacher
 */
public class VentanaSecundaria extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSecundaria
     */
    public VentanaSecundaria() {
        initComponents();
        this.setIconImage( new ImageIcon(getClass().getResource("/misventanasenlazadas/media/pato.png")).getImage() );
        System.out.println("He lanzado la Ventana Secundaria");
        this.setMinimumSize(new Dimension(140,130));
        setBounds(0,0,400,300);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana 2");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanelCentral.setLayout(new java.awt.BorderLayout());

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misventanasenlazadas/media/miniCat.png"))); // NOI18N
        jPanelCentral.add(jLabelImagen, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // Control "local" de efectos visuales
        // en la frontera del MVC, ya que no choca con el modelo de negocio
        System.out.println("X: " + this.getWidth() +"  Y: " + this.getHeight());
        try {
            //Ponemos a "Dormir" el programa durante los ms que queremos
            Thread.sleep(1*20);
         } catch (Exception e) {
            System.out.println(e);
         }
        jPanelCentral.setBackground(new Color(aleatorioX(),aleatorioY(),aleatorioZ()));
    }//GEN-LAST:event_formComponentResized



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanelCentral;
    // End of variables declaration//GEN-END:variables

// Fábrica de enteros aleatorio muy básica
    private int aleatorioX(){
        int tmp=0;
        double algo = 250 * Math.random();
        tmp = (int) algo;
        return tmp;
    }
    private int aleatorioY(){
        int tmp=0;
        double algo = 250 * Math.random();
        tmp = (int) algo;
        return tmp;
    }
    private int aleatorioZ(){
        int tmp=0;
        double algo = 250 * Math.random();
        tmp = (int) algo;
        return tmp;
    }

}
